### ISSUE TITLE
is there any way to pass name and click on Join Meeting button

### ISSUE THREAD

**Issue by vijupatil-1110** [jitsi/jitsi-meet-torture#323]
When we run the test with it is now asking to enter the name - "Please enter your name here " and click on "Join meeting" button.

So is there any way we can pass the name and click "Join meeting" button.

**Comment by damencho** [comment]
Please when you have problems or questions use the community forum before opening new issues.

That is already handled: https://github.com/jitsi/jitsi-meet-torture/blob/master/src/test/java/org/jitsi/meet/test/web/WebParticipant.java#L55

Otherwise, there is some code that already handles that as part of lobby test: https://github.com/jitsi/jitsi-meet-torture/blob/master/src/test/java/org/jitsi/meet/test/LobbyTest.java#L150
